debug = false
secret = "ee8ffbab66ac5297de597be2438c93bae162696e672e636f6d"
bind-to = "0.0.0.0:8443"
concurrency = 10240
tcp-buffer = "128kb"
prefer-ip = "prefer-ipv4"
domain-fronting-port = 8443
tolerate-time-skewness = "5s"

[network]
doh-ip = "8.8.8.8"
proxies = []

[network.timeout]
tcp = "5s"
http = "10s"
idle = "1m"

[defense.anti-replay]
enabled = true
max-size = "10mib"
error-rate = 0.001

[defense.blocklist]
enabled = true
download-concurrency = 64
urls = []
update-each = "24h"

[stats.statsd]
enabled = false
address = "127.0.0.1:8888"
metric-prefix = "mtg"
tag-format = "datadog"

[stats.prometheus]
enabled = false
bind-to = "127.0.0.1:3129"
http-path = "/"
metric-prefix = "mtg"
